title: "Part 2: Relevance Training - Getting started"
hero_image: images/banner3.png
description:  Part 2 of training for teachers introduces the first part of the resources for the Year 8 Relevance GBICi4 trial through a series of tasks
version: 4
listed: false
copyedit: false
last_tested: "2020-09-08"
steps:
  - title: Accessing the resources
  - title: Twelve sessions
  - title: Session resources
  - title: "Task 1: App idea development"
  - title: "Task 2: Paper designs and assets"
